### ISSUE TITLE
Console error, server crashes

### ISSUE THREAD

**Issue by Hazugg** [KP56/Fake-Players-Spigot-Plugin#7] opened 2021-04-30 18:19 UTC
As you will see in the image, I had previously reported the same thing they said that in this update they would fix it but it continues to persist, my server is 1.16.5 and I just put the command to summon, the server it shows a big error, crashes
![image](https://user-images.githubusercontent.com/31551514/116736606-ba9da380-a9b5-11eb-8a24-b686f09e71e0.png)

**Comment by KP56** [comment] 2021-05-01 12:22
Sorry, I thought it's the same issue as the PetBlocks one, which is fixed in this new version. Could I please get a list of your plugins? You can type /plugins in your console and copy the output text.

**Comment by Hazugg** [comment] 2021-05-01 16:45
My plugins
![image](https://user-images.githubusercontent.com/31551514/116789067-aec3e700-aa72-11eb-98b9-526eea2f9424.png)

**Comment by Hazugg** [comment] 2021-05-01 16:46
but I do not think it is plugin errors, I think it has to do with an incompatibility, since in itself it does not fall due to some complement itself, if not that the paper when executing the command falls altogether

**Comment by KP56** [comment] 2021-05-02 19:34
It's caused by incompatibility of fake players with some plugin - I'll need to figure out, which one is it.

**Comment by Hazugg** [comment] 2021-05-03 02:09
You could try with CMI that is base of the server is like an essentials 2

**Comment by KP56** [comment] 2021-05-03 08:40
Ok thank you for your help.

**Comment by KP56** [comment] 2021-05-04 07:03
By any chance, do you have an outdated protocollib?

**Comment by Hazugg** [comment] 2021-05-04 16:09
I'm using the latest version, but I'm going to try the development version for paper to see if it could be the problem

**Comment by Hazugg** [comment] 2021-05-04 16:20
I just installed the development version and the problem still persists

https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

![image](https://user-images.githubusercontent.com/31551514/117035922-820a0c80-acca-11eb-94d3-c7b02e93ec98.png)

**Comment by KP56** [comment] 2021-05-05 06:47
Ok, can I see the entire error? It should tell me, which plugin causes this issue.

**Comment by KP56** [comment] 2021-05-05 09:21
I think I know. I did some tests and it's a combination of Citizens and ProtocolLib, which causes these issues.

**Comment by KP56** [comment] 2021-05-05 10:42
https://drive.google.com/file/d/1bGdR8BkzgXV6KCpkhkwUz2oFZ4-CuuT-/view?usp=sharing

Try this version of Fake Players - maybe it will work.

**Comment by Hazugg** [comment] 2021-05-05 13:22
> Ok, ¿puedo ver el error completo? Debería decirme qué complemento causa este problema.

**Comment by KP56** [comment] 2021-05-05 13:41
Does it mean it works?

**Comment by Hazugg** [comment] 2021-05-05 13:55
I am testing with it is, first time I did summon I invoked a bot, but I wanted to do it again and I got the same error again, and what is valid is in itself that it is not an error of some plugin itself , of course what should cause some plugin I think, but if what happens is that the whole paper crashes

![image](https://user-images.githubusercontent.com/31551514/117149999-5e53ce80-ad7d-11eb-95e3-f3e9df46889b.png)

![image](https://user-images.githubusercontent.com/31551514/117150071-6f9cdb00-ad7d-11eb-87d6-2e03721a33aa.png)
![image](https://user-images.githubusercontent.com/31551514/117150167-85120500-ad7d-11eb-8028-c4aaa0853c37.png)


![image](https://user-images.githubusercontent.com/31551514/117150214-8fcc9a00-ad7d-11eb-93b0-a04b1e2d92e7.png)

when doing summon again as mentioned it gave the same error again
![image](https://user-images.githubusercontent.com/31551514/117150419-c1456580-ad7d-11eb-9d67-3314542b04df.png)
![image](https://user-images.githubusercontent.com/31551514/117150463-cacecd80-ad7d-11eb-8dc8-aeb5694aa8cc.png)


 I send you the complete error file: 

[CONSOLE ERROR.zip](https://github.com/KP56/Fake-Players-Spigot-Plugin/files/6427597/CONSOLE.ERROR.zip)

It is worth mentioning that it is not something from Citizens since I am testing on another server without that plugin and it continues to persist, of course I still have a protocol

**Comment by Hazugg** [comment] 2021-05-05 13:58
these are the plugins on the server that I am retesting

![image](https://user-images.githubusercontent.com/31551514/117152734-eb982280-ad7f-11eb-9f58-6a753955fb32.png)

**Comment by Hazugg** [comment] 2021-05-05 14:08
> Does it mean it works?

I closed it by mistake

**Comment by KP56** [comment] 2021-05-05 15:22
https://drive.google.com/file/d/1QAPI63bow0AJdCZEMfRH0zsP0kbFv3x6/view?usp=sharing

Maybe this one?

**Comment by KP56** [comment] 2021-05-05 15:48
I think you may be using an old/custom paper version. I'm so sorry for wasting so much of your time. Why haven't I realized it earlier? I decompiled the newest paper and I cannot find a b() function, which calls a writeAndFlush() function in a NetworkManager class (this is where the error is according to the stacktrace you provided). If it isn't a fork you paid for, you should definetely switch to purpur (https://github.com/pl3xgaming/Purpur).

**Comment by Hazugg** [comment] 2021-05-05 15:58
I tried what he sent me and the third summon failed again: /

I downloaded the paper from the same official page: https://papermc.io/
But if it is a matter of the paper then I will try updating it to the latest version or use the one you sent me, thank you!
![image](https://user-images.githubusercontent.com/31551514/117171169-42a5f380-ad90-11eb-8599-ad17ae8d8c62.png)

**Comment by KP56** [comment] 2021-05-05 16:08
I hope it is.

**Closed as completed** 2021-05-05 16:25 UTC
